### PR TITLE
Fix missing item date and description

### LINKED ISSUE #64: [Bug]: CNN fails to load
### Please try to fill out as much of the information below as you can. Thank you!

- [x] Yes, I've searched similar issues on GitHub and didn't find any.

### Which version contains the bug?

0.1.1

### Describe the bug

The CNN feed at `http://rss.cnn.com/rss/edition.rss` fails to load with the error:

<details>
  <summary>Error</summary>

Call to a member function getTimestamp() on null

#0 /icingaweb2/modules/feeds/library/Feeds/Web/Item.php(169): Icinga\Module\Feeds\Web\Item->getDate()
#1 /icingaweb2/modules/feeds/library/Feeds/Web/Item.php(197): Icinga\Module\Feeds\Web\Item->assembleHeader()
#2 /usr/local/src/ipl-html/src/HtmlDocument.php(344): Icinga\Module\Feeds\Web\Item->assemble()
#3 /usr/local/src/ipl-html/src/HtmlDocument.php(566): ipl\Html\HtmlDocument->ensureAssembled()
#4 /usr/local/src/ipl-html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
#5 /usr/local/src/ipl-html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#6 /usr/local/src/ipl-html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#7 /usr/local/src/ipl-html/src/HtmlDocument.php(568): ipl\Html\BaseHtmlElement->renderUnwrapped()
#8 /usr/local/src/ipl-html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
#9 /usr/local/src/ipl-html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#10 /usr/local/src/ipl-html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#11 /usr/local/src/ipl-html/src/HtmlDocument.php(568): ipl\Html\BaseHtmlElement->renderUnwrapped()
#12 /usr/local/src/ipl-html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
#13 /usr/local/src/ipl-html/src/HtmlDocument.php(568): ipl\Html\HtmlDocument->renderUnwrapped()
#14 /usr/local/src/ipl-web/src/Compat/ViewRenderer.php(62): ipl\Html\HtmlDocument->render()
#15 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action/Helper/ViewRenderer.php(970): ipl\Web\Compat\ViewRenderer->render()
#16 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#17 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action.php(533): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#18 /icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#19 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /icingaweb2/library/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#21 /icingaweb2/library/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#22 /icingaweb2/public/index.php(4): require_once(String)
#23 {main}
  
</details>

### How to recreate the bug?

1. Create a feed with this URL: `http://rss.cnn.com/rss/edition.rss`.
2. Try to view the feed.

### PR DESCRIPTION
**Pull request by martialblog**
Some guardrails when there are invalid items in a feed.

I switched to `new DateTime('@0')` so that these elements are not shown on top.

Fixed #64

### CODE REVIEW

File: library/Feeds/Parser/Result/FeedItem.php [hunk 1]
```diff
@@ -12,16 +12,16 @@ class FeedItem
...
     public ?string $creator = null;
     public ?string $image = null;
     public ?DateTime $date = null;
 
     public function compareDate(FeedItem $other): int
     {
-        $ad = $this->date ?? new DateTime('NOW');
-        $bd = $other->date ?? new DateTime('NOW');
+        $ad = $this->date ?? new DateTime('@0');
+        $bd = $other->date ?? new DateTime('@0');
```
Comment (TheSyscall) [inline library/Feeds/Parser/Result/FeedItem.php:24]: There is actually no need to create DateTime objects here at all.

Simply check if one of the elements is null before trying to compare.

File: library/Feeds/Web/Item.php [hunk 2]
```diff
@@ -103,7 +103,7 @@ protected function getCategoriesElement(): ?BaseHtmlElement
 
     protected function getContentElement(): ?BaseHtmlElement
     {
-        $text = $this->item->description;
+        $text = $this->item->description ?? '';
```
Comment (TheSyscall) [inline library/Feeds/Web/Item.php:106]: Description was defined as non-null in the same PR

File: library/Feeds/Web/Item.php [hunk 3]
```diff
@@ -122,7 +122,10 @@ protected function getLink(): ?string
 
     protected function getDate(): BaseHtmlElement
     {
-        return (new TimeAgo($this->item->date->getTimestamp()));
+        $d = $this->item->date;
+        $ts = $this->item->date !== null ? $this->item->date->getTimestamp() : 0;
+
+        return (new TimeAgo($ts));
```
Comment (TheSyscall) [inline library/Feeds/Web/Item.php:128]: Superfluous brackets

File: library/Feeds/Parser/Result/FeedItem.php [hunk 4]
```diff
@@ -12,16 +12,16 @@ class FeedItem
     public ?Feed $feed = null;
     public ?string $title = null;
     public ?string $link = null;
-    public ?string $description = null;
+    public string $description = '';
```
Comment (TheSyscall) [inline library/Feeds/Parser/Result/FeedItem.php:15]: Isn't null better than a sentinel value?
